package serverP4G;

/**
* serverP4G/ColumnHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public final class ColumnHolder implements org.omg.CORBA.portable.Streamable
{
  public serverP4G.Column value = null;

  public ColumnHolder ()
  {
  }

  public ColumnHolder (serverP4G.Column initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.ColumnHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.ColumnHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.ColumnHelper.type ();
  }

}
