package serverP4G;

/**
* serverP4G/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public serverP4G.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (serverP4G.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.GameHelper.type ();
  }

}
