package serverP4G;


/**
* serverP4G/GameData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public final class GameData implements org.omg.CORBA.portable.IDLEntity
{
  public serverP4G.GameState state = null;
  public char matrix[] = null;

  public GameData ()
  {
  } // ctor

  public GameData (serverP4G.GameState _state, char[] _matrix)
  {
    state = _state;
    matrix = _matrix;
  } // ctor

} // class GameData
