package serverP4G;

/**
* serverP4G/GameStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// etat du jeu
public final class GameStateHolder implements org.omg.CORBA.portable.Streamable
{
  public serverP4G.GameState value = null;

  public GameStateHolder ()
  {
  }

  public GameStateHolder (serverP4G.GameState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.GameStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.GameStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.GameStateHelper.type ();
  }

}
