package serverP4G;


/**
* serverP4G/ReturnCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// G_OVER - jeu termine, G_OPEN - jeu ouvert (manque d'un joueur), P_INV - joueur invalide
public class ReturnCode implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static serverP4G.ReturnCode[] __array = new serverP4G.ReturnCode [__size];

  public static final int _SUCCESS = 0;
  public static final serverP4G.ReturnCode SUCCESS = new serverP4G.ReturnCode(_SUCCESS);
  public static final int _WIN = 1;
  public static final serverP4G.ReturnCode WIN = new serverP4G.ReturnCode(_WIN);
  public static final int _XNULL = 2;
  public static final serverP4G.ReturnCode XNULL = new serverP4G.ReturnCode(_XNULL);
  public static final int _G_OVER = 3;
  public static final serverP4G.ReturnCode G_OVER = new serverP4G.ReturnCode(_G_OVER);
  public static final int _G_OPEN = 4;
  public static final serverP4G.ReturnCode G_OPEN = new serverP4G.ReturnCode(_G_OPEN);
  public static final int _P_INV = 5;
  public static final serverP4G.ReturnCode P_INV = new serverP4G.ReturnCode(_P_INV);

  public int value ()
  {
    return __value;
  }

  public static serverP4G.ReturnCode from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ReturnCode (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ReturnCode
