package serverP4G;


/**
* serverP4G/ReturnCodeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// G_OVER - jeu termine, G_OPEN - jeu ouvert (manque d'un joueur), P_INV - joueur invalide
abstract public class ReturnCodeHelper
{
  private static String  _id = "IDL:serverP4G/ReturnCode:1.0";

  public static void insert (org.omg.CORBA.Any a, serverP4G.ReturnCode that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static serverP4G.ReturnCode extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (serverP4G.ReturnCodeHelper.id (), "ReturnCode", new String[] { "SUCCESS", "WIN", "XNULL", "G_OVER", "G_OPEN", "P_INV"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static serverP4G.ReturnCode read (org.omg.CORBA.portable.InputStream istream)
  {
    return serverP4G.ReturnCode.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, serverP4G.ReturnCode value)
  {
    ostream.write_long (value.value ());
  }

}
