package serverP4G;


/**
* serverP4G/Column.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public class Column implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static serverP4G.Column[] __array = new serverP4G.Column [__size];

  public static final int _ONE = 0;
  public static final serverP4G.Column ONE = new serverP4G.Column(_ONE);
  public static final int _TWO = 1;
  public static final serverP4G.Column TWO = new serverP4G.Column(_TWO);
  public static final int _THREE = 2;
  public static final serverP4G.Column THREE = new serverP4G.Column(_THREE);
  public static final int _FOUR = 3;
  public static final serverP4G.Column FOUR = new serverP4G.Column(_FOUR);
  public static final int _FIVE = 4;
  public static final serverP4G.Column FIVE = new serverP4G.Column(_FIVE);
  public static final int _SIX = 5;
  public static final serverP4G.Column SIX = new serverP4G.Column(_SIX);
  public static final int _SEVEN = 6;
  public static final serverP4G.Column SEVEN = new serverP4G.Column(_SEVEN);

  public int value ()
  {
    return __value;
  }

  public static serverP4G.Column from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Column (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Column
