package serverP4G;


/**
* serverP4G/GameMatrixHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// donnees du jeu (etat + configuration en cours)
public final class GameMatrixHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public GameMatrixHolder ()
  {
  }

  public GameMatrixHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.GameMatrixHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.GameMatrixHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.GameMatrixHelper.type ();
  }

}
