package serverP4G;


/**
* serverP4G/GameState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// etat du jeu
public class GameState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static serverP4G.GameState[] __array = new serverP4G.GameState [__size];

  public static final int _CREATED = 0;
  public static final serverP4G.GameState CREATED = new serverP4G.GameState(_CREATED);
  public static final int _RUNNING = 1;
  public static final serverP4G.GameState RUNNING = new serverP4G.GameState(_RUNNING);
  public static final int _TERMINATED = 2;
  public static final serverP4G.GameState TERMINATED = new serverP4G.GameState(_TERMINATED);
  public static final int _ABANDONED = 3;
  public static final serverP4G.GameState ABANDONED = new serverP4G.GameState(_ABANDONED);

  public int value ()
  {
    return __value;
  }

  public static serverP4G.GameState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected GameState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class GameState
