package serverP4G;


/**
* serverP4G/GameStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// etat du jeu
abstract public class GameStateHelper
{
  private static String  _id = "IDL:serverP4G/GameState:1.0";

  public static void insert (org.omg.CORBA.Any a, serverP4G.GameState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static serverP4G.GameState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (serverP4G.GameStateHelper.id (), "GameState", new String[] { "CREATED", "RUNNING", "TERMINATED", "ABANDONED"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static serverP4G.GameState read (org.omg.CORBA.portable.InputStream istream)
  {
    return serverP4G.GameState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, serverP4G.GameState value)
  {
    ostream.write_long (value.value ());
  }

}
