package serverP4G;


/**
* serverP4G/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public interface GameOperations 
{

  // interface d'un jeu
  serverP4G.GameData getGameData ();
  String getGameId ();
  serverP4G.Players getPlayers ();

  // retourner la liste des joueurs connectes
  serverP4G.ReturnCode connectGame (String player);

  // demande de participation au jeu
  serverP4G.ReturnCode play (String player, serverP4G.Column col);

  // jetter un jeton
  boolean quitPlayer (String player);

  // joueur player quitte le jeu
  boolean ismyTurn (String player);
} // interface GameOperations
