package serverP4G;


/**
* serverP4G/GameDataHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

abstract public class GameDataHelper
{
  private static String  _id = "IDL:serverP4G/GameData:1.0";

  public static void insert (org.omg.CORBA.Any a, serverP4G.GameData that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static serverP4G.GameData extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = serverP4G.GameStateHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "state",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (42, _tcOf_members0 );
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (serverP4G.GameMatrixHelper.id (), "GameMatrix", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "matrix",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (serverP4G.GameDataHelper.id (), "GameData", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static serverP4G.GameData read (org.omg.CORBA.portable.InputStream istream)
  {
    serverP4G.GameData value = new serverP4G.GameData ();
    value.state = serverP4G.GameStateHelper.read (istream);
    value.matrix = serverP4G.GameMatrixHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, serverP4G.GameData value)
  {
    serverP4G.GameStateHelper.write (ostream, value.state);
    serverP4G.GameMatrixHelper.write (ostream, value.matrix);
  }

}
