package serverP4G;

/**
* serverP4G/GameDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public final class GameDataHolder implements org.omg.CORBA.portable.Streamable
{
  public serverP4G.GameData value = null;

  public GameDataHolder ()
  {
  }

  public GameDataHolder (serverP4G.GameData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.GameDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.GameDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.GameDataHelper.type ();
  }

}
