package serverP4G;


/**
* serverP4G/ListGamesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/


// chaque jeu a un identificateur unique
public final class ListGamesHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public ListGamesHolder ()
  {
  }

  public ListGamesHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.ListGamesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.ListGamesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.ListGamesHelper.type ();
  }

}
