package serverP4G;

/**
* serverP4G/PlayersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P4G.idl
* Thursday, March 10, 2016 4:04:26 PM ICT
*/

public final class PlayersHolder implements org.omg.CORBA.portable.Streamable
{
  public serverP4G.Players value = null;

  public PlayersHolder ()
  {
  }

  public PlayersHolder (serverP4G.Players initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = serverP4G.PlayersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    serverP4G.PlayersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return serverP4G.PlayersHelper.type ();
  }

}
